Repository katalon-studio/katalon-studio, pull requests merged in 2021-09, with the labels that each got.

#501 News Sep 01
  katalon-start-page/marketing-content.md
Labels: Extra Small

#502 Best Practices Sep 08
  katalon-start-page/best-practices.md
Labels: Extra Small

#504 Best Practices Sep 15
  katalon-start-page/best-practices.md
Labels: Extra Small

#505 Bump geckodriver to v0.30.0
  gecko-releases.json
Labels: Extra Large

#506 Temporarily remove support for Mac M1
  gecko-releases.json
Labels: Small

#508 Best Practices Sep 25
  katalon-start-page/best-practices.md
Labels: Extra Small
